name: Pull request checks for main
on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm install
      - run: npm run test:unit
  build-and-bundle:
    runs-on: ubuntu-latest
    name: Build and Bundle
    needs: 
      - unit-test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm install
    - run: npm run build
    - run: npm run bundle
